In [1]:
import pandas as pd
import numpy as np

# Data Loading
df = pd.read_csv("data/loan_data.csv")

print("Loaded successfully")
print(df.shape)

Loaded successfully
(32581, 12)

In [2]:
# Analysing dataset
df.head()
df.tail()
df.describe()
df.isna().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [3]:
# Finding outliers
df.describe()
df["person_age"].max()
df["person_emp_length"].max()

123.0

In [4]:
# Understanding Distributions
df["loan_status"].value_counts()

loan_status
0    25473
1     7108
Name: count, dtype: int64

In [5]:
# Understanding Cateogries
df["loan_grade"].unique()
df["loan_intent"].unique()
df["person_home_ownership"].unique()

array(['RENT', 'OWN', 'MORTGAGE', 'OTHER'], dtype=object)